home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

bucket_urls = [
	path('', views.BucketView.as_view(), name='bucket'),
	path('delete_obj/<str:key>/', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
	path('download_obj/<str:key>/', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
	path('bucket/', include(bucket_urls)),
	path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

one/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name='orders'
urlpatterns = [
	path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('payment/<int:order_id>/',views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
	path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(),name='cart_add'),
    path('cart/delete/<int:product_id>/',views.CartDeleteView.as_view(),name='cart_delete'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(),name='cart_remove'),
    path('cart/increase/<int:product_id>/',views.CartIncreaseView.as_view(),name='cart_increase'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from home.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.timezone import now

class Order(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='orders')
    paid=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=0)
    
    class Meta:
        ordering=('paid','-updated')
        
        
    def __str__(self):
        return f'{self.user} _ {str(self.id)}'
    
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.order_item.all())  
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total




class OrderItem(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='order_item')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    price=models.IntegerField()
    quantity=models.IntegerField(default=1)
    
    def __str__(self):
        return  f'{str(self.id)}'
         
    def get_cost(self):
        return (self.quantity)*(self.price)
         
        

class Coupon(models.Model):
	code = models.CharField(max_length=30, unique=True)
	valid_from = models.DateTimeField(default=now)
	valid_to = models.DateTimeField(default=now)
	discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
	active = models.BooleanField(default=False)

	def __str__(self):
		return self.code

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity=forms.IntegerField(min_value=1,max_value=9)
    
    
class CouponApplyForm(forms.Form):
    code=forms.CharField()

orders/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from . cart import Cart
from home.models import Product
from . forms import CartAddForm,CouponApplyForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Order,OrderItem,Coupon
from django.contrib import messages
import requests
from django.http import HttpResponse
import requests
import json
import datetime
from django.contrib import messages
from django.core.exceptions import PermissionDenied

class CartView(View):
    def get(self,request):
        cart=Cart(request)
        return render(request, 'orders/cart.html', {'cart':cart})


class CartAddView(View):
    def post(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        form=CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product,form.cleaned_data['quantity'])
        return redirect('orders:cart')
    
    
class CartDeleteView(View):
    def get(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        cart.delete(product)
        return redirect('orders:cart')
    
    
    
    
class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')
    
class CartIncreaseView(View):
    def get(self,request,product_id):
        cart=Cart(request)
        product=get_object_or_404(Product,id=product_id)
        cart.increase(product)
        return redirect('orders:cart')
    

class OrderDetailView(LoginRequiredMixin, View):
	form_class = CouponApplyForm

	def get(self, request, order_id):
		order = get_object_or_404(Order, id=order_id)
		return render(request, 'orders/payment.html', {'order':order,'form':self.form_class})




class OrderCreateView(LoginRequiredMixin, View):
	def get(self, request):
		cart = Cart(request)
		order = Order.objects.create(user=request.user)
		for item in cart:
			OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
		cart.get_total_price()
		return redirect('orders:order_detail', order.id)


MERCHANT = '****'
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"
CallbackURL = 'http://127.0.0.1:8000/orders/verify/'




class OrderPayView(LoginRequiredMixin, View):
	def get(self, request, order_id):
		cart=Cart(request)
		order = get_object_or_404(Order, id=order_id, user=request.user)
		cart.clear()
		cart.save()
		return render(request,'orders/order.html', {"order": order})


		# order = Order.objects.get(id=order_id)
		# request.session[''] = {
		# 	'order_id': order.id,
		# }
		# req_data = {
		# 	"merchant_id": MERCHANT,
		# 	"amount": order.get_total_price(),
		# 	"callback_url": CallbackURL,
		# 	"description": description,
		# 	"metadata": {"mobile": request.user.phone_number, "email": request.user.email}
		# }
		# req_header = {"accept": "application/json",
		# 			  "content-type": "application/json'"}
		# req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
		# 	req_data), headers=req_header)
		# authority = req.json()['data']['authority']
		# if len(req.json()['errors']) == 0:
		# 	return redirect(ZP_API_STARTPAY.format(authority=authority))
		# else:
		# 	e_code = req.json()['errors']['code']
		# 	e_message = req.json()['errors']['message']
		# 	return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


class OrderVerifyView(LoginRequiredMixin, View):
    pass
# 	def get(self, request):
# 		order_id = request.session['order_pay']['order_id']
# 		order = Order.objects.get(id=int(order_id))
# 		t_status = request.GET.get('Status')
# 		t_authority = request.GET['Authority']
# 		if request.GET.get('Status') == 'OK':
# 			req_header = {"accept": "application/json",
# 						  "content-type": "application/json'"}
# 			req_data = {
# 				"merchant_id": MERCHANT,
# 				"amount": order.get_total_price(),
# 				"authority": t_authority
# 			}
# 			req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
# 			if len(req.json()['errors']) == 0:
# 				t_status = req.json()['data']['code']
# 				if t_status == 100:
# 					order.paid = True
# 					order.save()
# 					return HttpResponse('Transaction success.\nRefID: ' + str(
# 						req.json()['data']['ref_id']
# 					))
# 				elif t_status == 101:
# 					return HttpResponse('Transaction submitted : ' + str(
# 						req.json()['data']['message']
# 					))
# 				else:
# 					return HttpResponse('Transaction failed.\nStatus: ' + str(
# 						req.json()['data']['message']
# 					))
# 			else:
# 				e_code = req.json()['errors']['code']
# 				e_message = req.json()['errors']['message']
# 				return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
# 		else:
# 			return HttpResponse('Transaction failed or canceled by user')





class CouponApplyView(View):
    form_class = CouponApplyForm

    def post(self, request, order_id):
        now = datetime.datetime.now()
        form = self.form_class(request.POST)

        if not form.is_valid():
            messages.error(request, "لطفاً کد تخفیف را درست وارد کنید.", "danger")
            return redirect('orders:order_detail', order_id)

        code = form.cleaned_data['code']
        
        try:
            coupon = Coupon.objects.get(code=code, valid_from__lte=now, valid_to__gte=now, active=True)
            order = get_object_or_404(Order, id=order_id, user=request.user)

            order.discount = coupon.discount if coupon.discount else 0
            order.save()

            messages.success(request, f'کد تخفیف {coupon.discount}% با موفقیت اعمال شد!', 'success')
        except Coupon.DoesNotExist:
            messages.error(request, "این کد تخفیف معتبر نیست!", "danger")

        return redirect('orders:order_detail', order_id)

orders/templates/orders/cart.html
{% extends "base.html" %}

 {% block content %}
 <div class="container my-5">
     <div class="card shadow-lg border-0 bg-light" style="border-radius: 15px;">
         <div class="card-header text-center bg-danger bg-opacity-10" style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
             <h2 class="fw-bold text-danger">🛍️ سبد خرید شما</h2>
         </div>
         <div class="card-body">
             <table class="table table-hover text-center align-middle">
                 <thead class="table-danger">
                     <tr>
                         <th scope="col">#</th>
                         <th scope="col">نام محصول</th>
                         <th scope="col">تعداد</th>
                         <th scope="col">قیمت واحد</th>
                         <th scope="col">قیمت کل</th>
                         <th scope="col">delete</th>
                     </tr>
                 </thead>
                 <tbody>
                     {% for item in cart %}
                     <tr>
                         <th scope="row">{{ forloop.counter }}</th>
                         <td class="fw-bold">{{ item.product }}</td>
                         <td>
                             <a href="{% url 'orders:cart_remove' item.product.id %}"  class="btn btn-sm btn-outline-danger rounded-circle">➖ </a>
                             <span class="mx-2">{{ item.quantity }}</span>
                             <a href="{% url 'orders:cart_increase' item.product.id %}" class="btn btn-sm btn-outline-success rounded-circle">➕</a>
                        </div>
                         </td>
                         <td class="text-success fw-bold">${{ item.price }}</td>
                         <td class="text-danger fw-bold">${{ item.total_price }}</td>
                         <td class="text-danger fw-bold"><a href="{% url 'orders:cart_delete' item.product.id %}">remove</a></td>
                     </tr>
                     {% endfor %}
                     <tr>
                       
                </tbody>
             </table>
         </div>
         <div class="text-end fw-bold fs-5 text-success my-3">
            جمع کل: ${{ cart.get_total_price }}
        </div>
         
         <div class="card-footer text-center bg-danger bg-opacity-10" style="border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;">
             <a  href="{% url 'home:home' %}" class="btn btn-danger px-4 py-2 fw-bold">🛒 ادامه خرید</a>
             <a href="{% url 'orders:order_create' %}" class="btn btn-success px-4 py-2 fw-bold">💳 پرداخت نهایی</a>
         </div>
     </div>
 </div>
 {% endblock content %}
 

orders/templates/orders/order.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style="max-width: 600px; background: #F2BED1; padding: 20px; border-radius: 10px; text-align: center;">
        <h2 style="color: #6A0572;">✅ سفارش شما با موفقیت ثبت شد!</h2>
        <p style="font-size: 18px; color: #6A0572;">شماره سفارش: <strong>{{ order.id }}</strong></p>
        <p style="font-size: 18px; color: #6A0572;">💰 مبلغ نهایی پرداخت شده: <strong>{{ order.get_total_price|floatformat:0 }} تومان</strong></p>
        <a href="{% url 'home:home' %}" class="btn btn-primary" style="margin-top: 15px;">🏠 بازگشت به صفحه اصلی</a>
    </div>
{% endblock %}

orders/templates/orders/payment.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 600px; background: #F2BED1; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2); text-align: center;">
    <h2 style="color: #6A0572;">💖 پرداخت سفارش</h2>
    <p style="color: #6A0572; font-size: 18px;">مبلغ قابل پرداخت: <strong>{{order.get_total_price }} تومان</strong></p>
    <p>شماره سفارش: <strong>{{ order.id }}</strong></p>
    <br>
    <p>مقدار تخفیف: <strong>{{ order.discount }}%</strong></p>
    
    <p style="font-size: 16px; color: #6A0572; font-weight: bold;">🎟️ آیا کد تخفیف دارید؟</p>

    <form action="{% url 'orders:apply_coupon' order.id %}" method="post"style="margin-bottom: 15px;">
        {% csrf_token %}
        <input type="text" name="code" placeholder="کد تخفیف را وارد کنید" style="
        padding: 8px;
        width: 70%;
        border: 2px solid #6A0572;
        border-radius: 5px;
        outline: none;
        text-align: center;" required >

        <button type="submit" style=" background: #FF4081;
        color: white;
        font-size: 16px;
        padding: 8px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;">
        ✔️ اعمال تخفیف</button>

    </form>

    <br>

    <a href="{% url 'orders:order_pay' order.id %}" class"btn" style="
    background: #FF4081;
    color: white;
    font-size: 18px;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: all 0.3s ease-in-out;">💳 پرداخت</a>

    <a href="{% url 'orders:cart' %}" style="display: block; margin-top: 10px; color: #6A0572; text-decoration: none;">🔙 بازگشت به سبد خرید</a>


</div>
{% endblock %}